<?php

const SERVICIO = "SERVICIO";
const SERVICIO_ID = "SERVICIO_ID";
const SERVICIO_NOMBRE = "SERVICIO_NOMBRE";
const SERVICIO_DESCRIPCION = "SERVICIO_DESCRIPCION";
const SERVICIO_PRECIO = "SERVICIO_PRECIO";
const SERVICIO_PROMOCION = "SERVICIO_PROMOCION";
